---
title: 'Deployment Workshop'
date: '2023-09-19T19:00:00+01:00'
description: |
  Join us for our Deployment Workshop where we'll demystify the process of taking your projects online.
  Regardless of technology or framework used, we'll tailor our guidance to your needs, ensuring a seamless deployment experience.
is_public: false
show_resources: true
meetings:
  - title: 'Around Meeting'
    description: 'The main room where we will meet'
    type: meeting
    url: 'https://around.co/r/techlabs-event'
forms: []
resources: []
